# Generated by Django 4.1 on 2022-08-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='nascimento',
            new_name='agenda',
        ),
    ]
