# Generated by Django 4.1 on 2022-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_alter_agenda_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agenda',
            field=models.DateTimeField(default=True),
        ),
    ]
